basePath: /api
definitions:
  dtos.ChangePasswordDTO:
    properties:
      new_password:
        example: newstrongpassword456
        type: string
      old_password:
        example: oldpassword123
        type: string
    type: object
  dtos.CreateSessionDTO:
    properties:
      email:
        example: john@example.com
        type: string
      password:
        example: strongpassword123
        type: string
    type: object
  dtos.ErrorDTO:
    properties:
      code:
        example: 400
        type: integer
      dev_message:
        example: Invalid request body format
        type: string
      message:
        example: Bad Request
        type: string
    type: object
  dtos.LevelDTO:
    properties:
      orders:
        type: integer
      price:
        type: number
      qty:
        type: integer
    type: object
  dtos.MarketDepthDTO:
    properties:
      asks:
        items:
          $ref: '#/definitions/dtos.LevelDTO'
        type: array
      bids:
        items:
          $ref: '#/definitions/dtos.LevelDTO'
        type: array
      exchange:
        example: NSE
        type: string
      ltp:
        example: 2450.75
        type: number
      symbol:
        example: RELIANCE
        type: string
    type: object
  dtos.SessionDTO:
    properties:
      user:
        $ref: '#/definitions/dtos.UserDTO'
    type: object
  dtos.SuccessDTO:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: OK
        type: string
    type: object
  dtos.SymbolDTO:
    properties:
      exchange:
        example: NSE
        type: string
      symbol:
        example: RELIANCE
        type: string
    type: object
  dtos.SymbolInfo:
    properties:
      exchange:
        example: NSE
        type: string
      symbol:
        example: RELIANCE
        type: string
    type: object
  dtos.SymbolListDTO:
    type: object
  dtos.SymbolStatusDTO:
    properties:
      symbols:
        items:
          $ref: '#/definitions/dtos.SymbolWithStatusDTO'
        type: array
    type: object
  dtos.SymbolWithStatusDTO:
    properties:
      exchange:
        example: NSE
        type: string
      last_close_price:
        example: "2430.50"
        type: string
      ltp:
        example: "2450.75"
        type: string
      symbol:
        example: RELIANCE
        type: string
    type: object
  dtos.UpdateUserDTO:
    properties:
      email:
        example: john@example.com
        type: string
      name:
        example: John Doe
        type: string
      phone_number:
        example: "+1234567890"
        type: string
      profile_picture_url:
        example: https://example.com/profile.jpg
        type: string
    type: object
  dtos.UserDTO:
    properties:
      created_at:
        example: "2023-10-01T12:00:00Z"
        type: string
      email:
        example: john@example.com
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      name:
        example: John Doe
        type: string
      phone_number:
        example: "+1234567890"
        type: string
      profile_picture_url:
        example: https://example.com/profile.jpg
        type: string
      updated_at:
        example: "2023-10-01T12:00:00Z"
        type: string
    type: object
  dtos.UserRegistrationDTO:
    properties:
      email:
        example: john@example.com
        type: string
      name:
        example: John Doe
        type: string
      password:
        example: strongpassword123
        type: string
    type: object
  dtos.WatchlistDTO:
    properties:
      index:
        example: 1
        type: integer
      symbols:
        items:
          $ref: '#/definitions/dtos.SymbolInfo'
        type: array
    type: object
host: localhost:3000
info:
  contact: {}
  description: Backend API for GMarket
  title: GMarket API
  version: "1.0"
paths:
  /market/depth:
    get:
      consumes:
      - application/json
      description: GetMarketDepth fetches the latest price, bid, and ask levels for
        a given symbol.
      parameters:
      - default: NSE
        description: Exchange (e.g., NSE)
        in: query
        name: exchange
        required: true
        type: string
      - default: RELIANCE
        description: Stock Symbol (e.g., RELIANCE)
        in: query
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.MarketDepthDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Get Market Depth Data
      tags:
      - market
  /market/symbols:
    get:
      description: GetSymbols serves the list of market symbols from a static JSON
        file.
      produces:
      - application/json
      responses:
        "200":
          description: ../data/stocks.json
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Get Market Symbols
      tags:
      - market
  /market/symbols/status:
    post:
      consumes:
      - application/json
      description: GetSymbolStatus fetches the latest trading price and last close
        price for a list of symbols.
      parameters:
      - description: List of Symbols
        in: body
        name: symbols
        required: true
        schema:
          $ref: '#/definitions/dtos.SymbolListDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.SymbolStatusDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Get Symbol Statuses
      tags:
      - market
  /sessions:
    delete:
      description: Delete the current session for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.SuccessDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Delete the current session (logout)
      tags:
      - sessions
    post:
      consumes:
      - application/json
      description: Create a new session for a user
      parameters:
      - description: User Login Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateSessionDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.SessionDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Create a new session (login)
      tags:
      - sessions
  /users:
    delete:
      description: Delete the currently authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.SuccessDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Delete current user
      tags:
      - users
    get:
      description: Retrieve information about the currently authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.UserDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Get current user
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update the information of the currently authenticated user
      parameters:
      - description: User Update Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.UserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Update current user information
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user with the provided information
      parameters:
      - description: User Registration Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.UserRegistrationDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.UserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Create a new user
      tags:
      - users
  /users/change-password:
    post:
      consumes:
      - application/json
      description: Change the password of the currently authenticated user
      parameters:
      - description: Change Password Data
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/dtos.ChangePasswordDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.SuccessDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Change user password
      tags:
      - users
  /users/is-authenticated:
    get:
      description: Check if the user is authenticated
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.SuccessDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Check authentication status
      tags:
      - users
  /watchlists/{watchlist_idx}:
    get:
      description: Retrieve the specified watchlist for the authenticated user
      parameters:
      - description: Watchlist Index (1-10)
        in: path
        name: watchlist_idx
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.WatchlistDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Get a user's watchlist
      tags:
      - watchlists
  /watchlists/{watchlist_idx}/symbols:
    delete:
      consumes:
      - application/json
      description: Remove a stock symbol from the specified watchlist for the authenticated
        user
      parameters:
      - description: Watchlist Index (1-10)
        in: path
        name: watchlist_idx
        required: true
        type: integer
      - description: Symbol to remove
        in: body
        name: symbol
        required: true
        schema:
          $ref: '#/definitions/dtos.SymbolDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.SuccessDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Remove a symbol from a user's watchlist
      tags:
      - watchlists
    post:
      consumes:
      - application/json
      description: Add a stock symbol to the specified watchlist for the authenticated
        user
      parameters:
      - description: Watchlist Index (1-10)
        in: path
        name: watchlist_idx
        required: true
        type: integer
      - description: Symbol to add
        in: body
        name: symbol
        required: true
        schema:
          $ref: '#/definitions/dtos.SymbolDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.SuccessDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Add a symbol to a user's watchlist
      tags:
      - watchlists
swagger: "2.0"
