basePath: /api
definitions:
  dtos.CreateSessionDTO:
    properties:
      email:
        example: john@example.com
        type: string
      password:
        example: strongpassword123
        type: string
    type: object
  dtos.ErrorDTO:
    properties:
      code:
        example: 400
        type: integer
      dev_message:
        example: Invalid request body format
        type: string
      message:
        example: Bad Request
        type: string
    type: object
  dtos.SessionDTO:
    properties:
      user:
        $ref: '#/definitions/dtos.UserDTO'
    type: object
  dtos.SymbolDTO:
    properties:
      exchange:
        example: NSE
        type: string
      symbol:
        example: RELIANCE
        type: string
    type: object
  dtos.SymbolInfo:
    properties:
      exchange:
        example: NSE
        type: string
      last_close_price:
        example: 2430.5
        type: number
      ltp:
        example: 2450.75
        type: number
      symbol:
        example: RELIANCE
        type: string
    type: object
  dtos.UserDTO:
    properties:
      created_at:
        example: "2023-10-01T12:00:00Z"
        type: string
      email:
        example: john@example.com
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      name:
        example: John Doe
        type: string
      phone_number:
        example: "+1234567890"
        type: string
      profile_picture_url:
        example: https://example.com/profile.jpg
        type: string
      updated_at:
        example: "2023-10-01T12:00:00Z"
        type: string
    type: object
  dtos.UserRegistrationDTO:
    properties:
      email:
        example: john@example.com
        type: string
      name:
        example: John Doe
        type: string
      password:
        example: strongpassword123
        type: string
    type: object
  dtos.WatchlistDTO:
    properties:
      index:
        example: 1
        type: integer
      symbols:
        items:
          $ref: '#/definitions/dtos.SymbolInfo'
        type: array
    type: object
host: localhost:3000
info:
  contact: {}
  description: Backend API for GMarket
  title: GMarket API
  version: "1.0"
paths:
  /market/chart:
    get:
      consumes:
      - application/json
      description: GetChartData fetches chart data for a given symbol from an external
        API.
      parameters:
      - default: NSE
        description: Exchange (e.g., NSE)
        in: query
        name: exchange
        required: true
        type: string
      - default: RELIANCE
        description: Stock Symbol (e.g., RELIANCE)
        in: query
        name: symbol
        required: true
        type: string
      - default: 1d
        description: Chart Range (e.g., 1d, 5d, 1mo)
        in: query
        name: range
        required: true
        type: string
      - default: 1m
        description: Data Interval (e.g., 1m, 5m, 1h)
        in: query
        name: interval
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Get Chart Data for a Symbol
      tags:
      - market
  /market/symbols:
    get:
      description: GetSymbols serves the list of market symbols from a static JSON
        file.
      produces:
      - application/json
      responses:
        "200":
          description: ../data/stocks.json
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Get Market Symbols
      tags:
      - market
  /sessions:
    delete:
      description: Delete the current session for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Delete the current session (logout)
      tags:
      - sessions
    post:
      consumes:
      - application/json
      description: Create a new session for a user
      parameters:
      - description: User Login Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateSessionDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.SessionDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Create a new session (login)
      tags:
      - sessions
  /users:
    delete:
      description: Delete the currently authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Delete current user
      tags:
      - users
    get:
      description: Retrieve information about the currently authenticated user
      produces:
      - application/json
      responses:
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Get current user
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user with the provided information
      parameters:
      - description: User Registration Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.UserRegistrationDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.UserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Create a new user
      tags:
      - users
  /watchlists/{watchlist_idx}:
    get:
      description: Retrieve the specified watchlist for the authenticated user
      parameters:
      - description: Watchlist Index (1-10)
        in: path
        name: watchlist_idx
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.WatchlistDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Get a user's watchlist
      tags:
      - watchlists
  /watchlists/{watchlist_idx}/symbols:
    delete:
      consumes:
      - application/json
      description: Remove a stock symbol from the specified watchlist for the authenticated
        user
      parameters:
      - description: Watchlist Index (1-10)
        in: path
        name: watchlist_idx
        required: true
        type: integer
      - description: Symbol to remove
        in: body
        name: symbol
        required: true
        schema:
          $ref: '#/definitions/dtos.SymbolDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Remove a symbol from a user's watchlist
      tags:
      - watchlists
    post:
      consumes:
      - application/json
      description: Add a stock symbol to the specified watchlist for the authenticated
        user
      parameters:
      - description: Watchlist Index (1-10)
        in: path
        name: watchlist_idx
        required: true
        type: integer
      - description: Symbol to add
        in: body
        name: symbol
        required: true
        schema:
          $ref: '#/definitions/dtos.SymbolDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorDTO'
      summary: Add a symbol to a user's watchlist
      tags:
      - watchlists
swagger: "2.0"
